// Locale data only; no rendering or application logic belongs in this file.
window.RECHARGE_PREVIEW_LOCALE = {
  ui: {
    title: "充值原生预览",
    brandSub: "哔哩哔哩漫画 · KOReader 插件",
    backGallery: "返回预览图集",
    eyebrow: "原生界面 · 合成场景",
    intro: "所有画面均由 KOReader 原生界面渲染，使用合成配置与合成账号。图中的金额、币数和订单状态仅为示例；示例二维码不能付款，未进行真实下单或实付验证。",
    sceneNav: "预览场景导航",
    searchLabel: "搜索场景",
    searchPlaceholder: "搜索名称或状态说明",
    mainFlow: "充值主流程",
    allStates: "全部状态",
    resolution: "图像尺寸",
    previous: "上一张",
    next: "下一张",
    openOriginal: "打开原图",
    zoom: "缩放",
    fit: "适应视图",
    nativePixels: "原始像素",
    close: "关闭",
    loading: "正在加载原生截图…",
    missingTitle: "此截图暂不可用",
    missingBody: "当前尺寸的截图未能加载，可能尚未取回或文件不匹配。请检查下方文件路径；这里不会换用其他场景的图片。",
    fixtureBadge: "合成配置与账号",
    syntheticBadge: "合成状态 · 无实付",
    footnote: "此图集仅展示 KOReader 原生界面的合成状态，不代表真实充值档位、币数、支付能力或到账结果。示例二维码不能付款。",
    keyboardHint: "使用左右方向键切换场景，按 Esc 关闭大图。",
    noMatches: "没有匹配的场景",
    unavailableData: "预览数据暂不可用",
    skip: "跳至预览内容",
    scenesCount: "共 {count} 个场景",
    imageAlt: "{title}，{size}，KOReader 原生界面合成截图",
    generatedNote: "截图来自隔离环境中的 KOReader 原生界面渲染，所有业务回调均为合成数据。",
    fallbackTitle: "其他充值状态",
    fallbackNote: "合成原生充值状态；请按场景文件名与原图核对。",
  },
  scenes: [
    {
      id: "recharge-account",
      title: "账户中的充值入口",
      note: "合成账号已登录且支持充值，原生账户页显示可用的充值入口。余额仅为场景数据。",
      main: true,
    },
    {
      id: "recharge-options",
      title: "选择充值金额",
      note: "原生弹窗展示合成配置中的可选金额与币数，仅用于预览档位选择布局。",
      main: true,
    },
    {
      id: "recharge-option-review",
      title: "确认所选金额",
      note: "选择合成档位后进入原生确认弹窗，展示金额与币数示例，并等待用户明确创建二维码。",
      main: true,
    },
    {
      id: "recharge-pending-no-expiry",
      title: "等待支付确认",
      note: "底部同一行并排显示“核对到账”和“关闭”。图中为合成订单，示例码不能付款。",
      main: true,
    },
    {
      id: "recharge-checking-credit",
      title: "正在查询到账状态",
      note: "合成订单进入原生查询状态，用于展示等待查询回调时的界面；未执行真实到账核验。",
      main: true,
    },
    {
      id: "recharge-credited",
      title: "到账完成的合成状态",
      note: "合成回调将订单标记为已到账，原生弹窗展示完成状态并隐藏二维码；不代表实付或真实到账。",
      main: true,
    },
    {
      id: "recharge-account-signed-out",
      title: "未登录时的充值入口",
      note: "合成账号切换为未登录状态，原生账户页禁用充值入口。",
      main: false,
    },
    {
      id: "recharge-config-loading",
      title: "正在读取充值配置",
      note: "原生弹窗等待合成配置回调，展示加载状态；此阶段尚未模拟创建订单。",
      main: false,
    },
    {
      id: "recharge-config-error",
      title: "配置读取失败",
      note: "合成网络错误触发原生失败提示和重新加载入口，界面不展示原始错误中的敏感字段。",
      main: false,
    },
    {
      id: "recharge-options-next-page",
      title: "更多充值金额",
      note: "原生金额选择弹窗的下一页展示其余合成档位，用于检查分页后的选择布局。",
      main: false,
    },
    {
      id: "recharge-manual-unavailable",
      title: "输入金额不在可选范围",
      note: "手动输入未列入合成配置的金额后，原生输入弹窗保留输入并提示重新选择。",
      main: false,
    },
    {
      id: "recharge-manual-review",
      title: "确认手动输入的金额",
      note: "手动输入匹配合成档位后，原生确认弹窗展示金额与币数示例，并等待明确确认。",
      main: false,
    },
    {
      id: "recharge-creating",
      title: "正在创建订单",
      note: "原生弹窗等待合成创建回调，显示创建中的状态并限制重复提交；尚无可展示的二维码。",
      main: false,
    },
    {
      id: "recharge-unknown-network",
      title: "查询结果暂不明确",
      note: "合成网络错误使原生弹窗显示订单仍未确认，保留同一订单并提供后续查询入口。",
      main: false,
    },
    {
      id: "recharge-new-order-notice",
      title: "开始另一笔充值前的提示",
      note: "合成订单完成后选择再次充值，原生弹窗说明新充值会使用另一笔订单。",
      main: false,
    },
    {
      id: "recharge-failed-not-submitted",
      title: "订单未提交",
      note: "合成创建结果标记为未提交，原生弹窗展示相应说明并隐藏二维码。",
      main: false,
    },
    {
      id: "recharge-unverified-code",
      title: "二维码地址未通过检查",
      note: "合成订单包含未通过检查的二维码地址，原生弹窗不将其渲染为可扫描二维码。",
      main: false,
    },
    {
      id: "recharge-pending-server-expiry",
      title: "待确认订单显示到期时间",
      note: "合成订单提供到期时间字段，原生弹窗展示该时间与示例二维码；示例码不能付款。",
      main: false,
    },
    {
      id: "recharge-expired-code",
      title: "二维码已过期",
      note: "合成订单的到期时间已过，原生弹窗隐藏二维码并保留对同一订单的查询入口。",
      main: false,
    },
    {
      id: "recharge-persistence-pending",
      title: "订单记录尚未保存",
      note: "合成订单带有待保存标记，原生弹窗展示保存警告；此场景不表示持久化存储已验证。",
      main: false,
    },
    {
      id: "recharge-creating-history",
      title: "记录列表中的创建状态",
      note: "关闭创建弹窗后，原生记录列表仍显示合成订单正在创建，并暂时禁用新充值入口。",
      main: false,
    },
    {
      id: "recharge-background-result-reopened",
      title: "重新打开后台返回的订单",
      note: "合成创建回调在弹窗关闭后返回，从原生记录列表重新打开该订单可查看示例二维码。",
      main: false,
    },
    {
      id: "recharge-orders-page-one",
      title: "充值记录第一页",
      note: "原生记录列表展示多笔合成订单的第一页，金额、状态和订单标识均为场景数据。",
      main: false,
    },
    {
      id: "recharge-orders-page-two",
      title: "充值记录第二页",
      note: "原生记录列表翻到第二页，展示其余合成订单及分页导航。",
      main: false,
    },
    {
      id: "recharge-history-selected-order",
      title: "查看选中的历史订单",
      note: "从原生记录列表选择指定合成订单后，详情弹窗展示该订单并保留完整订单标识。",
      main: false,
    },
    {
      id: "recharge-orders-empty",
      title: "当前账号没有充值记录",
      note: "合成记录集合为空，原生列表弹窗显示当前账号尚无已保存记录的说明。",
      main: false,
    },
    {
      id: "recharge-definitive-not-submitted",
      title: "创建请求未发出",
      note: "合成错误明确表示创建请求未提交，原生弹窗展示对应提示；此场景未生成付款订单。",
      main: false,
    },
    {
      id: "recharge-creation-unknown",
      title: "订单创建尚未确认",
      note: "合成创建请求未返回明确结果，原生弹窗提示状态不明并提供查看记录的入口。",
      main: false,
    },
    {
      id: "recharge-unknown-history",
      title: "记录列表中的未确认状态",
      note: "原生记录列表保留创建结果不明的合成订单，供后续查看；未进行真实订单核验。",
      main: false,
    },
    {
      id: "recharge-unrenderable-long-code",
      title: "付款码内容过长",
      note: "完整保留订单及原始链接，不截断链接生成错误付款码，也不会自动另建订单。",
      main: false,
    },
  ],
};
